### ISSUE TITLE
I get GoogleVR script-related errors when I try to launch Assets/B3d/Demos/Btc/Ocean/Scenes/world

### ISSUE THREAD

**Issue by syntheticperson** [KevinSmall/blockchain3d#2]
I cloned the repo:

https://github.com/KevinSmall/blockchain3d

And I'm using Unity 2018.2.61f (The instructions mention that 2018.1.0f2 or newer should work).

I first tried to launch Assets/B3d/Demos/Btc/Ocean/Scenes/world

I get many GoogleVR-related errors starting with:

Assets/GoogleVR/Scripts/Controller/Internal/Emulator/PhoneEvent.cs(19,12): error CS0400: The type or namespace name `Google' could not be found in the global namespace. Are you missing an assembly reference?

As I am initially interested in testing on Mac and IOS, is there an easy way I can remove the googleVR dependency to make these errors go away?

**Comment by syntheticperson** [comment]
I also get these errors/warnings:
Rebuilding Library because the asset database could not be found!
Removing Assets/GoogleVR/Demos/Environment/CubeRoom.obj because the asset does not exist
Removing Assets/GoogleVR/Demos/Models/HelloVR/Icosahedron.obj because the asset does not exist
Removing Assets/GoogleVR/Demos/Models/HelloVR/Materials because the asset does not exist
Removing Assets/GoogleVR/Demos/Models/HelloVR/QuadSphere.obj because the asset does not exist
etc

**Comment by KevinSmall** [comment]
Thanks for highlighting @syntheticperson, this was my fault for forgetting about a global gitignore.

Please take a fresh clone, the missing files are restored.

I can open world scene now and play without error.

**Comment by syntheticperson** [comment]
Hi Kevin,
Thanks for addressing third so quickly!
I'll try recloning. Will let you know if it works.

**Comment by syntheticperson** [comment]
That fixed it!
Much thanks! =D
